language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=dev-master

before_script:
  - echo 'date.timezone = "Europe/Sofia"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer require symfony/symfony:${SYMFONY_VERSION}
  - composer install

script: phpunit --coverage-text
