services:
    NetBull\CoreBundle\Form\Type\AjaxType:
        arguments: ['@doctrine.orm.entity_manager', '@router', '@parameter_bag']
        tags: ['form.type']

    NetBull\CoreBundle\Form\Type\AutoCollectionType:
        tags: ['form.type']

    NetBull\CoreBundle\Form\Type\DynamicType:
        arguments: ['@doctrine.orm.entity_manager']
        tags: ['form.type']

    NetBull\CoreBundle\Form\Type\EntityHiddenType:
        arguments: ['@doctrine.orm.entity_manager']
        tags: ['form.type']

    NetBull\CoreBundle\Form\Type\MoneyType:
        tags: ['form.type']

    NetBull\CoreBundle\Form\Type\PhoneNumberType:
        tags: ['form.type']

    NetBull\CoreBundle\Form\Type\PointTextType:
        tags: ['form.type']

    NetBull\CoreBundle\Form\Type\PointType:
        tags: ['form.type']

    NetBull\CoreBundle\Form\Type\Select2Type:
        arguments: ['@doctrine.orm.entity_manager', '@router', '@parameter_bag']
        tags: ['form.type']
